### ISSUE TITLE
Gas optics fail for profiles that do not span both upper and lower atmosphere

### ISSUE THREAD

**Issue by brhillman** [RobertPincus/rte-rrtmgp#3]
Gas optics routines will currently fail when passed any profiles that do not span both the upper and lower atmosphere, as defined by the value of `press_ref_trop` in the coefficients files. This appears to be due to a bug in the `interpolation` routine in `mo_gas_optics_kernels`, where if the threshold between the lower and upper atmosphere is not crossed, the arrays `itropo_lower` and `itropo_upper` are left unset (in my case, these were left with values of zero, but this is probably compiler-dependent since they do not appear to be explicitly initialized anywhere). The code in question seems to be the following:
```
        ! itropo = 1 lower atmosphere; itropo = 2 upper atmosphere
        itropo = merge(1,2,tropo(icol,ilay))
        if (ilay .eq. 1) then
          itropo_last(icol) = itropo
        endif
        if (itropo_last(icol) .ne. itropo) then
          if (itropo .eq. 1) then ! layers go from TOA to surface
            itropo_lower(icol,1) = ilay
            itropo_lower(icol,2) = nlay
            itropo_upper(icol,1) = 1
            itropo_upper(icol,2) = ilay - 1
            itropo_last(icol) = itropo
          else ! layers go from surface to TOA
            itropo_lower(icol,1) = 1
            itropo_lower(icol,2) = ilay - 1
            itropo_upper(icol,1) = ilay
            itropo_upper(icol,2) = nlay
            itropo_last(icol) = itropo
          endif
        endif
```
This causes problems in `gas_optical_depths_minor`, where the values of `itropo` are used to set the loop indices over the vertical dimension of the column gas amounts. If either `itropo_lower` or `itropo_uppter` contain zeros, then this code will create a segmentation fault when trying to access the `col_gas` array out of bounds.

**Comment by RobertPincus** [comment]
Hi Ben - 

Thanks for pointing this out. I'll put a test for this in our regression testing framework. This is a part of the code where we have larger-scale plans: basically we want to re-write the absorption-by-major-gases code to look more like the minor gas code. As people are on/going on holiday you can expect a fix in early Sept. 

- Robert

**Comment by RobertPincus** [comment]
Hi Ben - 

I've made a first attempt at solving this problem. Please see branch hotfix-gas-optics-layer-index. 

- Robert

**Comment by RobertPincus** [comment]
I believe the two merges above fix this problem. Please let me know if not.
