### ISSUE TITLE
mo_load_coefficients opens files for *writing* instead of just reading

### ISSUE THREAD

**Issue by brhillman** [RobertPincus/rte-rrtmgp#31]
In examples/mo_load_coefficients, the coefficients files are opened with mode `NF90_WRITE`. Since these files are not intended to be written to, they should probably be open in mode `NF90_NOWRITE`.

**Comment by RobertPincus** [comment]
Fixed on develop in commit 5f3aeb46cd5e4991f3255c7e3714dbef1934c238.
