### ISSUE TITLE
Large diffs from baseline files on master

### ISSUE THREAD

**Issue by mrnorman** [RobertPincus/rte-rrtmgp#35]
When I run the master branch:

```
[imn@login5:/gpfs/alpine/scratch/imn/stf006/rte-rrtmgp] 8-) git branch
* master
[imn@login5:/gpfs/alpine/scratch/imn/stf006/rte-rrtmgp] 8-) git diff
[imn@login5:/gpfs/alpine/scratch/imn/stf006/rte-rrtmgp] 8-) 
```

with PGI on Summit using `-O1`, I get the following diffs for a CPU run:

```
Variable rld differs (max abs difference: 3.814697e-06; max frac. difference: 1.178709e-05%)
Variable rsu differs (max abs difference: 4.685364e-01; max frac. difference: 1.464250e-01%)
Variable rsd differs (max abs difference: 1.940063e+00; max frac. difference: 1.464253e-01%)
```

I'm thinking maybe the baseline files are stale compared to current master.

**Comment by RobertPincus** [comment]
You are correct about the cause. Updates to come.
---
Robert Pincus
University of Colorado/NOAA Earth System Research Lab
http://cires.colorado.edu/researcher/robert-pincus

On Aug 5, 2019, at 10:21 AM, Matt Norman <notifications@github.com<mailto:notifications@github.com>> wrote:


When I run the master branch:

[imn@login5:/gpfs/alpine/scratch/imn/stf006/rte-rrtmgp] 8-) git branch
* master
[imn@login5:/gpfs/alpine/scratch/imn/stf006/rte-rrtmgp] 8-) git diff
[imn@login5:/gpfs/alpine/scratch/imn/stf006/rte-rrtmgp] 8-)


with PGI on Summit using -O1, I get the following diffs:

Variable rld differs (max abs difference: 3.814697e-06; max frac. difference: 1.178709e-05%)
Variable rsu differs (max abs difference: 4.685364e-01; max frac. difference: 1.464250e-01%)
Variable rsd differs (max abs difference: 1.940063e+00; max frac. difference: 1.464253e-01%)


I'm thinking maybe the baseline files are stale compared to current master.
