### ISSUE TITLE
Error in dimension size (documentation or code)

### ISSUE THREAD

**Issue by charleskawczynski** [RobertPincus/rte-rrtmgp#52]
In the [comments](https://github.com/RobertPincus/rte-rrtmgp/blob/master/rte/mo_source_functions.F90#L29-L30), `lev_source_inc`, `lev_source_dec` are claimed to have a second dimension of size `nlay+1`, but when [allocated](https://github.com/RobertPincus/rte-rrtmgp/blob/master/rte/mo_source_functions.F90#L101-L102), the size is only `nlay`.

**Comment by RobertPincus** [comment]
Fixed in commit ce295e5 to master.
