### ISSUE TITLE
Verify index

### ISSUE THREAD

**Issue by charleskawczynski** [RobertPincus/rte-rrtmgp#63]
This is more of a question than an issue, is the index for `ilev` in `tau(:,ilev,igpt)` correct [here](https://github.com/RobertPincus/rte-rrtmgp/blob/master/rte/kernels/mo_rte_solver_kernels.F90#L317)? Based on when `top_at_1` is true, it looks like there might be a `+1` missing, but I'm not sure.

**Comment by RobertPincus** [comment]
@charleskawczynski This code is present for completeness and doesn't get called in any of our test cases, but I think it's correct. Note that fluxes are defined with vertical dimension `nlay+1 = nlev` while `tau` is defined with vertical dimension `nlay`. So flux on the second level of fluxes, `nlay=nlev-1`, is `exp(-tau(nlay) /mu0)`

Certainly we could make this more clear by adopting `lay` or `lev` uniformly through the routine.
